repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.79.9
    hooks:
      - id: cfn-lint
        files: template.yaml

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.287"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]

  - repo: https://github.com/python-poetry/poetry
    rev: "1.6.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-export
        args:
          [
            "--without-hashes",
            "--only",
            "main",
            "--format",
            "requirements.txt",
            "--output",
            "src/requirements.txt",
          ]
