AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM FastAPI Application

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.11
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:45

Resources:
  HandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      CodeUri: src
      Description: Mangum Handler Function
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyPath:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: FastAPI
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
      Tags:
        LambdaPowertools: python

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod environment for Mangum Handler Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  HandlerFunction:
    Description: "Mangum Handler Function ARN"
    Value: !GetAtt HandlerFunction.Arn
