from pathlib import Path

from fastapi import (
    FastAPI,
    Request,
)
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates


def mount_frontend(app: FastAPI, build_dir: Path, assets_folder="assets") -> FastAPI:
    """Serves a frontend application at the root path `/`

    Args:
        app: FastAPI application instance
        build_dir: Frontend build directory
            (generated by `yarn build` or `npm run build`)

    Returns:
        FastAPI: instance with the frontend application mounted
    """
    app.mount(
        f"/{assets_folder}/",
        StaticFiles(directory=(build_dir / assets_folder), html=True),
        name="assets",
    )

    templates = Jinja2Templates(directory=build_dir)

    @app.get("/{_full_path:path}", include_in_schema=False)
    async def serve_frontend(request: Request, _full_path: str) -> HTMLResponse:
        return templates.TemplateResponse("index.html", {"request": request})

    return app
